# Generated by Django 4.1.1 on 2023-03-29 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('character_detail', '0001_initial'),
        ('characters', '0001_initial'),
        ('ethnicity', '0001_initial'),
        ('professions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterdetail',
            name='character',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='characters.character'),
        ),
        migrations.AddField(
            model_name='characterdetail',
            name='ethnicity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ethnicity.ethnicity'),
        ),
        migrations.AddField(
            model_name='characterdetail',
            name='profession',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='professions.profession'),
        ),
    ]
