# Generated by Django 4.1 on 2022-09-14 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contexto', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Snippet',
            new_name='Contexto',
        ),
    ]
