# Generated by Django 4.1.1 on 2022-10-27 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professions', '0001_initial'),
        ('races', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameGroup', models.CharField(max_length=25)),
                ('namePlayer', models.CharField(max_length=25)),
                ('profession', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='professions.profession')),
                ('race', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='races.race')),
            ],
        ),
    ]
