# Generated by Django 4.1.1 on 2023-03-31 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ethnicity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticsUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.IntegerField()),
                ('intelligence', models.IntegerField()),
                ('dexterity', models.IntegerField()),
                ('charisma', models.IntegerField()),
                ('wisdom', models.IntegerField()),
                ('constitucion', models.IntegerField()),
                ('ethnicity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ethnicity.ethnicity')),
            ],
        ),
    ]
