# Generated by Django 4.1.1 on 2023-04-03 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticsUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.IntegerField()),
                ('intelligence', models.IntegerField()),
                ('dexterity', models.IntegerField()),
                ('charisma', models.IntegerField()),
                ('wisdom', models.IntegerField()),
                ('constitucion', models.IntegerField()),
                ('ethnicityType', models.CharField(choices=[('GOD_OF_SUN', 'God of Sun'), ('GOD_OF_DEATH', 'God of Death'), ('GOD_OF_MOON', 'God of Moon'), ('GOD_OF_EARTH', 'God of Earth')], max_length=50)),
            ],
        ),
    ]
