# Generated by Django 4.1.1 on 2023-05-28 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adventures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('adventure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adventures.adventures')),
            ],
        ),
    ]
