# Generated by Django 4.1.1 on 2023-03-29 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0001_initial'),
        ('adventures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventures',
            name='character',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.character'),
        ),
    ]
