# Generated by Django 4.1.1 on 2023-05-28 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoopDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.IntegerField()),
                ('content_type', models.CharField(choices=[('CONTEXTO', 'Contexto'), ('ACCION', 'Accion'), ('RESULTADO', 'Resultado')], max_length=30)),
                ('loop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loop.loop')),
            ],
        ),
    ]
